# Generated by Django 4.2.7 on 2024-04-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventureMeetup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_Name', models.CharField(max_length=200)),
                ('event_location', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField()),
                ('event_description', models.TextField()),
                ('event_host_name', models.TextField()),
                ('event_cost', models.TextField()),
                ('event_number_of_attendees', models.IntegerField(default=0)),
                ('event_external_url', models.URLField(blank=True)),
            ],
        ),
    ]
