# Generated by Django 4.2.7 on 2024-04-28 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_Name', models.CharField(max_length=200)),
                ('event_location', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField()),
                ('event_description', models.TextField()),
                ('event_host_name', models.TextField()),
                ('event_cost', models.TextField()),
                ('event_number_of_attendees', models.IntegerField(default=0)),
                ('event_external_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='* Full Name *', max_length=100)),
                ('city', models.CharField(help_text='* City *', max_length=50)),
                ('state', models.CharField(help_text='* State *', max_length=50)),
                ('users_email', models.EmailField(help_text='Email address', max_length=254)),
                ('instagram_username', models.CharField(blank=True, help_text='Instagram', max_length=30)),
                ('facebook_username', models.CharField(blank=True, help_text='FaceBook', max_length=30)),
                ('linkedin_username', models.CharField(blank=True, help_text='LinkedIn', max_length=30)),
                ('interests', models.TextField(blank=True, help_text='Let us know about your interests!')),
                ('events_attended', models.IntegerField(default=0)),
                ('user', models.OneToOneField(help_text='Create your username!', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
