# Generated by Django 4.2.7 on 2024-04-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventureApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofile',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='city',
            field=models.CharField(blank=True, help_text='* City *', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='state',
            field=models.CharField(blank=True, help_text='* State *', max_length=50),
        ),
    ]
