# Generated by Django 4.2.7 on 2024-04-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventureApp', '0004_alter_usersprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='events_images/'),
        ),
    ]
